{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "da24332c",
   "metadata": {},
   "source": [
    "### Basic Formating\n",
    "- _Italic_ : Unterstrich vor und nach dem Wort ansetzten (_not_)\n",
    "- **bold**: Doppelter Stern vor und nach das Wort, um das Wort fett gedruckt wiedergegeben zu kriegen (**not**)\n",
    "\n",
    "### Headings\n",
    "- Überschriften von 1 bis 6, während 1 die größte und 6 die kleinste ist\n",
    "- Heading 1 wird durch ein Hashtag (#) verwirklicht, Heading 2 durch zwei Hashtags (##) etc.\n",
    "- Header 1 und 6 sollten nicht zu oft benutzt werden\n",
    "\n",
    "### Links\n",
    "- **inline link: Text in \"[Text]\" schreiben und der Link in \"(link)\" runde Klammern\n",
    "- emphasis links \n",
    "\n",
    "### Reference Links\n",
    "- Link zu einem anderen \"Place\"\n",
    "- Beispiel:\n",
    "\n",
    "Do you want to [see something fun][a fun place]?\n",
    "\n",
    "Well, do I have [the website for you][another fun place]\n",
    "\n",
    "[a fun place]: www.zombo.com\n",
    "[another fun place]: www.stumbleupon.com\n",
    "\n",
    "### Images\n",
    "#### 1. style: _inline image style_ \n",
    "- anfangen mit ! und text in \"[]\" link in \"()\"\n",
    "\n",
    "Beispiel:\n",
    "\n",
    "![A pretty tiger](https://upload.wikimedia.org/wikipedia/commons/5/56/Tiger.50.jpg)\n",
    "\n",
    "#### Text zu Bild einfügen (Sehbehinderte)\n",
    "![Black cat][Black]\n",
    "\n",
    "![Orange cat][Orange]\n",
    "\n",
    "[Black]: https://upload.wikimedia.org/wikipedia/commons/a/a3/81_INF_DIV_SSI.jpg\n",
    "\n",
    "[Orange]: http://icons.iconarchive.com/icons/google/noto-emoji-animals-nature/256/22221-cat-icon.png\n",
    "\n",
    "\n",
    "### Blockquotes\n",
    "- für besondere Aufmerksamkeit/Design/Quelle/Artikel\n",
    "- Paragraph oder spezielle Formatierung für Aufmerksamkeit\n",
    "- Zitat o.a. mit > anfangen\n",
    "\n",
    "I read this interesting quote the other day:\n",
    "\n",
    "> \"Her eyes had called him and his soul had leaped at the call. To live, to err, to fall, to triumph, to recreate life out of life!\"\n",
    "\n",
    "### Lange Blockquotes\n",
    "\n",
    ">Once upon a time and a very good time it was there was a moocow coming down along the road and this moocow that was coming down along the road met a nicens little boy named baby tuckoo...\n",
    ">\n",
    ">His father told him that story: his father looked at him through a glass: he had a hairy face.\n",
    ">\n",
    ">He was baby tuckoo. The moocow came down the road where Betty Byrne lived: she sold lemon platt.\n",
    "\n",
    "### Listen\n",
    "- geordnete & ungeordnete\n",
    "\n",
    "#### Geordnete Listen\n",
    "- Listen mit Nummern (1,2,3...)\n",
    "1. Cut the cheese\n",
    "2. Slice the tomatoes\n",
    "3. Rub the tomatoes in flour\n",
    "\n",
    "#### Ungeordnete Listen\n",
    "- Listen mit Bullet points\n",
    "* Flour\n",
    "* Cheese\n",
    "* Tomatoes\n",
    "\n",
    "### Verschachtelte Listen\n",
    "* Zeilen einschieben nach rechts \n",
    "  * also wie hier\n",
    "\n",
    "\n",
    "### Paragraphen (Leerzeile) in Listen\n",
    "- Paragraphen einrücken um 1 nach rechts\n",
    "- Leerzeile überhalb freilassen\n",
    "\n",
    "### Paragraphen in Listen (hard break)\n",
    "Unter den Absätzen eine Leerzeile freilassen\n",
    "\n",
    "Sowie hier\n",
    "\n",
    "### Paragraphen in Listen (soft break)\n",
    "- zwei Leerzeichen nach Sätzen \n",
    "- keine Leerzeilen nötig\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
